//! `pyscf/gto/mole.py:BSE_META` — the auxiliary-basis recommendations of
//! the Basis Set Exchange, reduced to the four fields
//! `df.addons.bse_predefined_auxbasis` reads.
//!
//! 95 of BSE_META's 689 entries carry auxiliaries; the rest are omitted
//! because the lookup returns `None` for them either way.

/// `(orbital_basis_alias, jkfit, jfit, dftjfit, rifit)`. The alias key is
/// already `_format_basis_name`-canonical (lower-cased, punctuation stripped).
/// `(orbital_basis_alias, jkfit, jfit, dftjfit, rifit)`.
pub type BseAuxRow = (
    &'static str,
    Option<&'static str>,
    Option<&'static str>,
    Option<&'static str>,
    Option<&'static str>,
);

pub const BSE_AUXBASIS: [BseAuxRow; 95] = [
    ("6311g(d,p)", None, None, None, Some("6-311g_st__st_-rifit")),
    ("6311g**", None, None, None, Some("6-311g_st__st_-rifit")),
    ("631g(d,p)", None, None, None, Some("6-31g_st__st_-rifit")),
    ("631g**", None, None, None, Some("6-31g_st__st_-rifit")),
    ("augccpv(5+d)z", None, None, None, Some("aug-cc-pv5z-rifit")),
    ("augccpv(d+d)z", None, None, None, Some("aug-cc-pvdz-rifit")),
    ("augccpv(q+d)z", None, None, None, Some("aug-cc-pvqz-rifit")),
    ("augccpv(t+d)z", None, None, None, Some("aug-cc-pvtz-rifit")),
    ("augccpv5z", Some("cc-pv5z-jkfit"), None, None, Some("aug-cc-pv5z-rifit")),
    ("augccpv5zpp", None, None, None, Some("aug-cc-pv5z-pp-rifit")),
    ("augccpv6z", None, None, None, Some("aug-cc-pv6z-rifit")),
    ("augccpvdz", None, None, None, Some("aug-cc-pvdz-rifit")),
    ("augccpvdzpp", None, None, None, Some("aug-cc-pvdz-pp-rifit")),
    ("augccpvqz", Some("cc-pvqz-jkfit"), None, None, Some("aug-cc-pvqz-rifit")),
    ("augccpvqzpp", None, None, None, Some("aug-cc-pvqz-pp-rifit")),
    ("augccpvtz", Some("cc-pvtz-jkfit"), None, None, Some("aug-cc-pvtz-rifit")),
    ("augccpvtzpp", None, None, None, Some("aug-cc-pvtz-pp-rifit")),
    ("augccpwcv5z", None, None, None, Some("aug-cc-pwcv5z-rifit")),
    ("augccpwcv5zpp", None, None, None, Some("aug-cc-pwcv5z-pp-rifit")),
    ("augccpwcvdz", None, None, None, Some("aug-cc-pwcvdz-rifit")),
    ("augccpwcvdzpp", None, None, None, Some("aug-cc-pwcvdz-pp-rifit")),
    ("augccpwcvqz", None, None, None, Some("aug-cc-pwcvqz-rifit")),
    ("augccpwcvqzpp", None, None, None, Some("aug-cc-pwcvqz-pp-rifit")),
    ("augccpwcvtz", None, None, None, Some("aug-cc-pwcvtz-rifit")),
    ("augccpwcvtzpp", None, None, None, Some("aug-cc-pwcvtz-pp-rifit")),
    ("augpcseg1", None, None, None, None),
    ("augpcseg2", None, None, None, None),
    ("augpcseg3", None, None, None, None),
    ("ccpcvdzf12", None, None, None, Some("cc-pcvdz-f12-rifit")),
    ("ccpcvqzf12", None, None, None, Some("cc-pcvqz-f12-rifit")),
    ("ccpcvtzf12", None, None, None, Some("cc-pcvtz-f12-rifit")),
    ("ccpv(5+d)z", None, None, None, Some("cc-pv5z-rifit")),
    ("ccpv(d+d)z", None, None, None, Some("cc-pvdz-rifit")),
    ("ccpv(q+d)z", None, None, None, Some("cc-pvqz-rifit")),
    ("ccpv(t+d)z", None, None, None, Some("cc-pvtz-rifit")),
    ("ccpv5z", Some("cc-pv5z-jkfit"), None, None, Some("cc-pv5z-rifit")),
    ("ccpv5zpp", None, None, None, Some("cc-pv5z-pp-rifit")),
    ("ccpv6z", None, None, None, Some("cc-pv6z-rifit")),
    ("ccpvdz", None, None, None, Some("cc-pvdz-rifit")),
    ("ccpvdzf12", None, None, None, None),
    ("ccpvdzpp", None, None, None, Some("cc-pvdz-pp-rifit")),
    ("ccpvqz", Some("cc-pvqz-jkfit"), None, None, Some("cc-pvqz-rifit")),
    ("ccpvqzf12", None, None, None, None),
    ("ccpvqzpp", None, None, None, Some("cc-pvqz-pp-rifit")),
    ("ccpvtz", Some("cc-pvtz-jkfit"), None, None, Some("cc-pvtz-rifit")),
    ("ccpvtzf12", None, None, None, None),
    ("ccpvtzpp", None, None, None, Some("cc-pvtz-pp-rifit")),
    ("ccpwcv5z", None, None, None, Some("cc-pwcv5z-rifit")),
    ("ccpwcv5zpp", None, None, None, Some("cc-pwcv5z-pp-rifit")),
    ("ccpwcvdz", None, None, None, Some("cc-pwcvdz-rifit")),
    ("ccpwcvdzpp", None, None, None, Some("cc-pwcvdz-pp-rifit")),
    ("ccpwcvqz", None, None, None, Some("cc-pwcvqz-rifit")),
    ("ccpwcvqzpp", None, None, None, Some("cc-pwcvqz-pp-rifit")),
    ("ccpwcvtz", None, None, None, Some("cc-pwcvtz-rifit")),
    ("ccpwcvtzpp", None, None, None, Some("cc-pwcvtz-pp-rifit")),
    ("def2qzvp", Some("def2-universal-jkfit"), Some("def2-universal-jfit"), None, Some("def2-qzvp-rifit")),
    ("def2qzvpp", Some("def2-universal-jkfit"), Some("def2-universal-jfit"), None, Some("def2-qzvpp-rifit")),
    ("def2qzvppd", None, None, None, Some("def2-qzvppd-rifit")),
    ("def2sv(p)", Some("def2-sv(p)-jkfit"), Some("def2-universal-jfit"), None, Some("def2-sv(p)-rifit")),
    ("def2svp", Some("def2-universal-jkfit"), Some("def2-universal-jfit"), None, Some("def2-svp-rifit")),
    ("def2svpd", None, None, None, Some("def2-svpd-rifit")),
    ("def2tzvp", Some("def2-universal-jkfit"), Some("def2-universal-jfit"), None, Some("def2-tzvp-rifit")),
    ("def2tzvpd", None, None, None, Some("def2-tzvpd-rifit")),
    ("def2tzvpp", Some("def2-universal-jkfit"), Some("def2-universal-jfit"), None, Some("def2-tzvpp-rifit")),
    ("def2tzvppd", None, None, None, Some("def2-tzvppd-rifit")),
    ("dgaussdzvp", None, None, Some("dgauss-a1-dftjfit"), None),
    ("dgaussdzvp2", None, None, Some("dgauss-a2-dftjfit"), None),
    ("dgausstzvp", None, None, Some("dgauss-a2-dftjfit"), None),
    ("pcseg1", None, None, None, None),
    ("pcseg2", None, None, None, None),
    ("pcseg3", None, None, None, None),
    ("sarc2qzvdkh2", Some("sarc2-qzv-dkh2-jkfit"), None, None, None),
    ("sarc2qzvpdkh2", Some("sarc2-qzvp-dkh2-jkfit"), None, None, None),
    ("sarc2qzvpzora", Some("sarc2-qzvp-zora-jkfit"), None, None, None),
    ("sarc2qzvzora", Some("sarc2-qzv-zora-jkfit"), None, None, None),
    ("x2cqzvpall", None, Some("x2c-jfit"), None, None),
    ("x2cqzvpall2c", None, Some("x2c-jfit"), None, None),
    ("x2cqzvpall2cs", None, Some("x2c-jfit"), None, None),
    ("x2cqzvpalls", None, Some("x2c-jfit"), None, None),
    ("x2cqzvppall", None, Some("x2c-jfit"), None, None),
    ("x2cqzvppall2c", None, Some("x2c-jfit"), None, None),
    ("x2cqzvppall2cs", None, Some("x2c-jfit"), None, None),
    ("x2cqzvppalls", None, Some("x2c-jfit"), None, None),
    ("x2csv(p)all", None, Some("x2c-jfit"), None, None),
    ("x2csv(p)all2c", None, Some("x2c-jfit"), None, None),
    ("x2csv(p)alls", None, Some("x2c-jfit"), None, None),
    ("x2csvpall", None, Some("x2c-jfit"), None, None),
    ("x2csvpall2c", None, Some("x2c-jfit"), None, None),
    ("x2csvpalls", None, Some("x2c-jfit"), None, None),
    ("x2ctzvpall", None, Some("x2c-jfit"), None, None),
    ("x2ctzvpall2c", None, Some("x2c-jfit"), None, None),
    ("x2ctzvpalls", None, Some("x2c-jfit"), None, None),
    ("x2ctzvppall", None, Some("x2c-jfit"), None, None),
    ("x2ctzvppall2c", None, Some("x2c-jfit"), None, None),
    ("x2ctzvppalls", None, Some("x2c-jfit"), None, None),
];
