//! Plan 09-04 — `pyscf-pbc-tools::mesh` (port of `pyscf/pbc/tools/pbc.py:787-836`).
//!
//! `pyscf-pbc-tools` sits BELOW `pyscf-pbc-gto` in the dependency graph, so it
//! cannot reach the §9.2 reference `Cell`s. The lattices below are the same
//! five systems' `cell.lattice_vectors()` in Bohr, pasted as literals from the
//! upstream run that produced `crates/pyscf-pbc-gto/tests/cutoff.rs`'s
//! references (D-PBC-19).
//!
//! Tier 1 (invariants):
//!   * the Householder `|R[2,2]|` agrees with its closed form
//!     `|det(M)| / ||c0 x c1||` on random and lattice-shaped inputs;
//!   * `qr_heights` reproduces the reciprocal-cell heights
//!     `2*pi / |a_i . n_jk|` for any lattice;
//!   * every mesh axis is odd, monotone in the cutoff, and never
//!     under-resolves;
//!   * `mesh_to_cutoff` inverts `cutoff_to_mesh` up to the `ceil`;
//!   * `cutoff_to_gs` / `gs_to_cutoff` are the documented aliases;
//!   * a singular lattice and a negative cutoff are errors, not NaN.
//!
//! Tier 2: `cutoff_to_mesh` and `mesh_to_cutoff` against hard-coded upstream
//! values. NOTE the lattices here are UPSTREAM's, so these are exact-value
//! comparisons at 1e-12 — the `pyscf_core::Unit::Ang` gap documented in
//! `pyscf-pbc-gto/tests/cell_build.rs` enters only when a `Cell` builds the
//! lattice from Angstrom, which this crate never does.

use pyscf_pbc_tools::mesh::{
    cutoff_to_gs, cutoff_to_mesh, gs_to_cutoff, mesh_to_cutoff, qr_heights, qr_r22_abs,
    qr_r22_abs_closed_form,
};
use std::f64::consts::PI;

/// `cell.lattice_vectors()` in Bohr for the five §9.2 systems, from live PySCF
/// 2.12.1. Generated by the snippet in `pyscf-pbc-gto/tests/cutoff.rs`.
const LATTICES: [(&str, [[f64; 3]; 3]); 5] = [
    (
        "diamond",
        [
            [0.0, 3.3701375705493315, 3.3701375705493315],
            [3.3701375705493315, 0.0, 3.3701375705493315],
            [3.3701375705493315, 3.3701375705493315, 0.0],
        ],
    ),
    (
        "si",
        [
            [0.0, 5.131173346031512, 5.131173346031512],
            [5.131173346031512, 0.0, 5.131173346031512],
            [5.131173346031512, 5.131173346031512, 0.0],
        ],
    ),
    (
        "lif",
        [
            [0.0, 3.8077981409986, 3.8077981409986],
            [3.8077981409986, 0.0, 3.8077981409986],
            [3.8077981409986, 3.8077981409986, 0.0],
        ],
    ),
    (
        "he_fcc",
        [
            [0.0, 2.8345891868475928, 2.8345891868475928],
            [2.8345891868475928, 0.0, 2.8345891868475928],
            [2.8345891868475928, 2.8345891868475928, 0.0],
        ],
    ),
    (
        "graphene",
        [
            [4.648726266430052, 0.0, 0.0],
            [-2.324363133215026, 4.025915041968412, 0.0],
            [0.0, 0.0, 37.79452249130124],
        ],
    ),
];

fn rel(a: f64, b: f64) -> f64 {
    let scale = a.abs().max(b.abs());
    if scale == 0.0 {
        0.0
    } else {
        (a - b).abs() / scale
    }
}

/// Deterministic LCG (Knuth/MMIX constants) — same generator the other suites
/// use, so "random" inputs are reproducible without pulling in `rand`.
struct Lcg(u64);
impl Lcg {
    fn next_f64(&mut self) -> f64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((self.0 >> 11) as f64) / ((1_u64 << 53) as f64) * 2.0 - 1.0
    }
}

// =========================================================================
// TIER 1 — invariants.
// =========================================================================

/// The Householder factorization and the closed form `|det| / ||c0 x c1||` are
/// two independent routes to `|R[2,2]|`. If either is wrong they diverge.
#[test]
fn householder_r22_agrees_with_the_closed_form() {
    let mut rng = Lcg(0x5DEECE66D);
    for _ in 0..2000 {
        let cols = [
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
        ];
        let closed = qr_r22_abs_closed_form(&cols);
        // Skip near-degenerate draws where both routes are dominated by
        // cancellation rather than by either algorithm.
        if !closed.is_finite() || closed < 1e-3 {
            continue;
        }
        let house = qr_r22_abs(&cols);
        assert!(
            rel(house, closed) < 1e-9,
            "|R22| disagree: householder {house:.17e} vs closed {closed:.17e} for {cols:?}"
        );
    }
}

/// Same check on the real reciprocal lattices, at a much tighter tolerance —
/// these are well conditioned.
#[test]
fn r22_routes_agree_on_the_reference_lattices() {
    for (name, a) in LATTICES {
        let r = qr_heights(&a).expect("non-singular");
        // Rebuild b to feed the closed form the identical columns.
        let heights = closed_form_heights(&a);
        for i in 0..3 {
            assert!(
                rel(r[i], heights[i]) < 1e-13,
                "{name} axis {i}: {} vs closed {}",
                r[i],
                heights[i]
            );
        }
    }
}

/// `qr_heights(a)[i] == 2*pi / ||a_i||`, exactly, for ANY lattice.
///
/// `b_i . a_j = 2*pi*delta_ij` by construction, so `a_2` is the (only)
/// direction orthogonal to both `b_0` and `b_1`; the component of `b_2`
/// perpendicular to `span(b_0, b_1)` is therefore `b_2 . a_2 / ||a_2|| =
/// 2*pi / ||a_2||`, and the same argument permutes to the other two axes. That
/// identity is completely independent of the QR route and pins every height to
/// a one-line closed form.
#[test]
fn qr_heights_equal_two_pi_over_the_lattice_vector_lengths() {
    for (name, a) in LATTICES {
        let r = qr_heights(&a).expect("non-singular");
        for i in 0..3 {
            let want = 2.0 * PI / norm(&a[i]);
            assert!(
                rel(r[i], want) < 1e-14,
                "{name} axis {i}: qr height {} vs 2*pi/||a_{i}|| {}",
                r[i],
                want
            );
        }
    }
    // ... and on random lattices, where a wrong column permutation could not
    // hide behind the reference cells' symmetry.
    let mut rng = Lcg(0xDEADBEEF);
    for _ in 0..500 {
        let a = [
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
            [rng.next_f64(), rng.next_f64(), rng.next_f64()],
        ];
        if det3(&a).abs() < 1e-2 {
            continue;
        }
        let r = qr_heights(&a).expect("non-singular");
        for i in 0..3 {
            let want = 2.0 * PI / norm(&a[i]);
            assert!(
                rel(r[i], want) < 1e-9,
                "axis {i}: {} vs {want} for {a:?}",
                r[i]
            );
        }
    }
}

/// `2*ceil(Gmax) + 1` — odd, at least 1, never shrinking as the cutoff rises,
/// and exactly `[1,1,1]` at zero cutoff.
#[test]
fn mesh_is_odd_and_monotone() {
    for (name, a) in LATTICES {
        assert_eq!(cutoff_to_mesh(&a, 0.0).expect("ok"), [1, 1, 1], "{name}");
        let mut last = [0_usize; 3];
        for ke in [1.0, 10.0, 50.0, 100.0, 500.0, 2000.0] {
            let m = cutoff_to_mesh(&a, ke).expect("ok");
            for i in 0..3 {
                assert_eq!(m[i] % 2, 1, "{name} axis {i}: {} is not odd", m[i]);
                assert!(m[i] >= last[i], "{name} axis {i} shrank at ke = {ke}");
            }
            last = m;
        }
    }
}

/// `mesh_to_cutoff(cutoff_to_mesh(a, ke)) >= ke`, and the mesh one step
/// smaller would NOT reach it — i.e. `cutoff_to_mesh` returns the minimal
/// sufficient odd mesh.
#[test]
fn cutoff_to_mesh_is_the_minimal_sufficient_mesh() {
    for (name, a) in LATTICES {
        for ke in [5.0, 50.0, 100.0, 422.9, 1077.5] {
            let m = cutoff_to_mesh(&a, ke).expect("ok");
            let up = mesh_to_cutoff(&a, m).expect("ok");
            for i in 0..3 {
                assert!(
                    up[i] >= ke,
                    "{name} axis {i}: mesh {} resolves {} < {ke}",
                    m[i],
                    up[i]
                );
                if m[i] >= 3 {
                    let smaller = {
                        let mut s = m;
                        s[i] -= 2;
                        s
                    };
                    let down = mesh_to_cutoff(&a, smaller).expect("ok");
                    assert!(
                        down[i] < ke,
                        "{name} axis {i}: mesh {} would already reach {ke}; \
                         cutoff_to_mesh is not minimal",
                        smaller[i]
                    );
                }
            }
        }
    }
}

/// `gs = mesh // 2` and `gs_to_cutoff(gs) == mesh_to_cutoff(2*gs+1)`
/// (`pbc.py:830-836`).
#[test]
fn gs_helpers_are_the_documented_aliases() {
    for (name, a) in LATTICES {
        for ke in [50.0, 100.0, 400.0] {
            let mesh = cutoff_to_mesh(&a, ke).expect("ok");
            let gs = cutoff_to_gs(&a, ke).expect("ok");
            for i in 0..3 {
                assert_eq!(gs[i], mesh[i] / 2, "{name} axis {i}");
            }
            let a_ = gs_to_cutoff(&a, gs).expect("ok");
            let b_ = mesh_to_cutoff(&a, [2 * gs[0] + 1, 2 * gs[1] + 1, 2 * gs[2] + 1]).expect("ok");
            assert_eq!(a_, b_, "{name}");
        }
    }
}

/// `mesh_to_cutoff` uses `gs = (mesh - 1) // 2`, so an even mesh resolves the
/// same cutoff as the odd one below it, and a mesh of 0 or 1 resolves nothing.
#[test]
fn mesh_to_cutoff_floors_to_the_odd_mesh_below() {
    let a = LATTICES[0].1;
    assert_eq!(
        mesh_to_cutoff(&a, [16, 16, 16]).expect("ok"),
        mesh_to_cutoff(&a, [15, 15, 15]).expect("ok")
    );
    assert_eq!(mesh_to_cutoff(&a, [1, 1, 1]).expect("ok"), [0.0, 0.0, 0.0]);
    assert_eq!(mesh_to_cutoff(&a, [0, 0, 0]).expect("ok"), [0.0, 0.0, 0.0]);
}

/// A singular lattice and a bad cutoff are errors, never NaN meshes.
#[test]
fn degenerate_inputs_are_errors() {
    let singular = [[1.0, 2.0, 3.0], [2.0, 4.0, 6.0], [1.0, 0.0, 1.0]];
    assert!(cutoff_to_mesh(&singular, 100.0).is_err());
    assert!(mesh_to_cutoff(&singular, [15, 15, 15]).is_err());
    assert!(qr_heights(&singular).is_err());

    let a = LATTICES[0].1;
    assert!(cutoff_to_mesh(&a, -1.0).is_err());
    assert!(cutoff_to_mesh(&a, f64::NAN).is_err());
    assert!(cutoff_to_mesh(&a, f64::INFINITY).is_err());
}

/// A cubic lattice of side `L` has `b_i = 2*pi/L * e_i`, so every height is
/// `2*pi/L` and the mesh is isotropic — a case whose answer can be written down
/// by hand.
#[test]
fn cubic_lattice_has_the_analytic_mesh() {
    let l = 10.0_f64;
    let a = [[l, 0.0, 0.0], [0.0, l, 0.0], [0.0, 0.0, l]];
    let r = qr_heights(&a).expect("ok");
    for (i, ri) in r.iter().enumerate() {
        assert!(rel(*ri, 2.0 * PI / l) < 1e-15, "axis {i}: {ri}");
    }
    for ke in [10.0_f64, 100.0, 1000.0] {
        let want = ((2.0 * ke).sqrt() / (2.0 * PI / l)).ceil() as usize * 2 + 1;
        assert_eq!(cutoff_to_mesh(&a, ke).expect("ok"), [want, want, want]);
    }
}

// =========================================================================
// TIER 2 — hard-coded upstream references (D-PBC-19).
//
// Generated with `.venv/bin/python` against PySCF 2.12.1:
//
//   from pyscf.pbc.tools import pbc as pbctools
//   pbctools.cutoff_to_mesh(a, ke)        # -> MESH_REF
//   pbctools.mesh_to_cutoff(a, [15]*3)    # -> KE_REF
//
// where `a` is the matching row of LATTICES.
// =========================================================================

/// `cutoff_to_mesh(a, ke)` for ke in {50, 100, 200}.
const MESH_REF: [(&str, [[usize; 3]; 3]); 5] = [
    ("diamond", [[17, 17, 17], [23, 23, 23], [33, 33, 33]]),
    ("si", [[25, 25, 25], [35, 35, 35], [49, 49, 49]]),
    ("lif", [[19, 19, 19], [27, 27, 27], [37, 37, 37]]),
    ("he_fcc", [[15, 15, 15], [21, 21, 21], [27, 27, 27]]),
    ("graphene", [[17, 17, 123], [23, 23, 173], [31, 31, 243]]),
];

/// `mesh_to_cutoff(a, [15,15,15])`, all three axes.
const KE_REF: [(&str, [f64; 3]); 5] = [
    (
        "diamond",
        [42.579500924406574, 42.579500924406574, 42.57950092440661],
    ),
    (
        "si",
        [18.36802459047572, 18.36802459047571, 18.368024590475716],
    ),
    (
        "lif",
        [33.35400506797271, 33.35400506797271, 33.35400506797271],
    ),
    (
        "he_fcc",
        [60.188784545382006, 60.188784545381985, 60.188784545381964],
    ),
    (
        "graphene",
        [44.756680952842046, 44.75668095284208, 0.6771238261355474],
    ),
];

#[test]
fn cutoff_to_mesh_matches_upstream() {
    for (name, a) in LATTICES {
        let want = MESH_REF.iter().find(|(n, _)| *n == name).expect("row").1;
        for (k, ke) in [50.0_f64, 100.0, 200.0].into_iter().enumerate() {
            assert_eq!(
                cutoff_to_mesh(&a, ke).expect("ok"),
                want[k],
                "{name}: cutoff_to_mesh(a, {ke})"
            );
        }
    }
}

#[test]
fn mesh_to_cutoff_matches_upstream() {
    for (name, a) in LATTICES {
        let want = KE_REF.iter().find(|(n, _)| *n == name).expect("row").1;
        let got = mesh_to_cutoff(&a, [15, 15, 15]).expect("ok");
        for i in 0..3 {
            assert!(
                rel(got[i], want[i]) < 1e-12,
                "{name} axis {i}: got {:.17e}, upstream {:.17e}, rel {:.3e}",
                got[i],
                want[i],
                rel(got[i], want[i])
            );
        }
    }
}

/// The deprecated `cutoff_to_gs(a, 100.0)` (`= mesh // 2`) against upstream.
#[test]
fn cutoff_to_gs_matches_upstream() {
    const GS_REF: [(&str, [usize; 3]); 5] = [
        ("diamond", [11, 11, 11]),
        ("si", [17, 17, 17]),
        ("lif", [13, 13, 13]),
        ("he_fcc", [10, 10, 10]),
        ("graphene", [11, 11, 86]),
    ];
    for (name, a) in LATTICES {
        let want = GS_REF.iter().find(|(n, _)| *n == name).expect("row").1;
        assert_eq!(cutoff_to_gs(&a, 100.0).expect("ok"), want, "{name}");
    }
}

// --- small local vector helpers, so this file needs no other imports -------

fn det3(m: &[[f64; 3]; 3]) -> f64 {
    m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
        - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
        + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0])
}

fn cross(u: &[f64; 3], v: &[f64; 3]) -> [f64; 3] {
    [
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    ]
}

fn norm(v: &[f64; 3]) -> f64 {
    (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt()
}

/// The closed-form `|R[2,2]|` per axis, built from the same reciprocal vectors
/// `qr_heights` uses — the independent route for
/// [`r22_routes_agree_on_the_reference_lattices`].
fn closed_form_heights(a: &[[f64; 3]; 3]) -> [f64; 3] {
    let b = reciprocal_2pi(a);
    [
        qr_r22_abs_closed_form(&[b[1], b[2], b[0]]),
        qr_r22_abs_closed_form(&[b[2], b[0], b[1]]),
        qr_r22_abs_closed_form(&[b[0], b[1], b[2]]),
    ]
}

/// `2*pi*inv(a.T)`, one reciprocal vector per row — written out here rather
/// than imported so the check does not share code with the implementation.
fn reciprocal_2pi(a: &[[f64; 3]; 3]) -> [[f64; 3]; 3] {
    // b_i = 2*pi * (a_j x a_k) / det(a), the standard reciprocal-basis formula.
    let det = det3(a);
    let mut b = [[0.0_f64; 3]; 3];
    for (i, bi) in b.iter_mut().enumerate() {
        let c = cross(&a[(i + 1) % 3], &a[(i + 2) % 3]);
        for (t, bit) in bi.iter_mut().enumerate() {
            *bit = 2.0 * PI * c[t] / det;
        }
    }
    b
}
